steps:
  # 1. Install dependencies
  - name: "node:20"
    entrypoint: "npm"
    args: ["install"]

  # 2. Prisma generate
  - name: "node:20"
    entrypoint: "npx"
    args: ["prisma", "generate"]

  # 3. Prisma migrate
  - name: "node:20"
    entrypoint: "npx"
    args: ["prisma", "migrate", "deploy"]
    env:
      - DATABASE_URL=${_DATABASE_URL}

  # 4. Build TypeScript
  - name: "node:20"
    entrypoint: "npm"
    args: ["run", "build"]

  # 5. Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/backend-festify/front-end-festify:$COMMIT_SHA
      - .

  # 6. Push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/backend-festify/front-end-festify:$COMMIT_SHA

  # 7. Deploy ke Cloud Run dengan image yang benar
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - run
      - deploy
      - front-end-festify
      - --image
      - asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/backend-festify/front-end-festify:$COMMIT_SHA
      - --region
      - asia-southeast2
      - --platform
      - managed
      - --set-env-vars
      - DATABASE_URL=${_DATABASE_URL}

substitutions:
  _DATABASE_URL: ""