steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/backend-repo/backend:$COMMIT_SHA'
      - '.'

  # Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/backend-repo/backend:$COMMIT_SHA'

  # Deploy ke Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - backend-service
      - --image
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/backend-repo/backend:$COMMIT_SHA'
      - --region
      - asia-southeast2
      - --platform
      - managed